export const enum EntityAttrType {
    Text = 'text',
    Password = 'password',
    Numeric = 'numeric',
    Textarea = 'textarea',
    Select = 'select',
    Checkbox = 'tcheckboxext',
    Radio = 'radio',
    RadioGroup = 'radioGroup',
    DateTime = 'dateTime',
    Date = 'date',
    Time = 'time',
    Tel = 'tel',
    Url = 'url',
  }